name: Static code checkers

on: [push]

permissions: {}

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run mypy --install-types --non-interactive .

  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run pyright

  ruff:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # needed for SARIF uploads
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run ruff check --output-format sarif > results.sarif  
    - uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f  # v3.28.18
      with:
        sarif_file: results.sarif
        category: zizmor

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run flake8
