name: Static code checkers

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run mypy --install-types --non-interactive .

  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run pyright

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run ruff check lib/ tests/
