name: Static code checkers

on: [push]

permissions: {}

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run mypy --install-types --non-interactive .

  pyright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run pyright

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run ruff check lib/ tests/
