name: Check coding style

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run flake8

  pydocstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run pydocstyle
