name: Check requirements file consistency

on: [push]

permissions: {}

jobs:
  requirements-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
      with:
        version: "0.7.x"
    - run: uv sync --frozen
    - run: uv run ./requirements/update_requirements.py
    - run: git diff --exit-code
